- name: Set WireGuard Netplan Facts
  set_fact:
    wireguard_config_facts: 
      interfaces: |
          {
            {% for interface in new_wireguard_interfaces %}
            "{{ interface.name }}": {{ interface }},
            {% endfor %}
          }

- name: Convert Peers to Dict
  set_fact: 
    wireguard_config_facts: "{{ wireguard_config_facts | combine(update_dict, recursive=true) }}"
  loop: "{{ wireguard_config_facts.interfaces | dict2items }}"
  loop_control:
    loop_var: interface_item
    label: "{{ interface_item.key }}"
  vars:
    interface:
      name: "{{ interface_item.value.name }}"
      config: "{{ interface_item.value }}"
    peers_dict: | 
      {
          {% for peer in interface.config.peers %}
          "{{ peer.name }}__{{ peer.interface }}": {{ peer }},
          {% endfor %}
      }
    update_dict:
      interfaces: |
        {
          "{{ interface.name }}": {
            {% if interface.config.peers is defined %}
            "peers": {
              {% for peer in interface.config.peers %}
              "{{ peer.name }}__{{ peer.interface }}": {{ peer }},
              {% endfor %}
            },
            {% endif %}
            {% if interface.config.unmanaged_peers is defined %}
            "unmanaged_peers": {
              {% for peer in interface.config.unmanaged_peers %}
              "{{ peer.name }}": {{ peer }},
              {% endfor %}
            },
            {% endif %}
          }
        }

- name: Debug
  debug: 
    msg: "{{ wireguard_config_facts }}"

- name: Handle Key Facts
  include_tasks:
    file: new_wireguard_keys.yml
    apply:
      vars:
        interface:
          name: "{{ interface_item.value.name }}"
          config: "{{ interface_item.value }}"
  loop: "{{ wireguard_config_facts.interfaces | dict2items }}"
  loop_control:
    label: "{{ interface_item.key }}"
    loop_var: interface_item
  when:
    - interface_item.value.state | default('present') != 'absent'

- name: Debug 2
  debug: 
    msg: "{{ wireguard_config_facts }}"

- name: Handle Peers Facts
  include_tasks:
    file: new_wireguard_peers.yml
    apply:
      vars:
        interface:
          name: "{{ interface_item.value.name }}"
          config: "{{ interface_item.value }}"
  loop: "{{ wireguard_config_facts.interfaces | dict2items }}"
  loop_control:
    label: "{{ interface_item.key }}"
    loop_var: interface_item
  when:
    - interface_item.value.state | default('present') != 'absent'

- name: Debug 3
  debug: 
    msg: "{{ wireguard_config_facts }}"